version: '3.6'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
    - ./scripts/data.sql:/docker-entrypoint-initdb.d/10-init.sql
